apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: basic-cluster
  region: us-east-2

managedNodeGroups:
  - name: node-t4g
    labels: { role: workers }
    instanceType: t4g.medium
    desiredCapacity: 2
    volumeSize: 20
    privateNetworking: true
  