version: '3.9'
services:

  postgres:
    image: postgres:12.2
    environment:
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
  
  
  prometheus:
    image: prom/prometheus
    network_mode: "host" # acesso local no host
    # ports:
    #   - "9090:9090"  
    volumes:
       - ./prometheus.yml:/etc/prometheus/prometheus.yml
  
  grafana:
    image: grafana/grafana-oss
    network_mode: "host" # acesso local no host
    # ports:
    #   - "3000:3000"

  jaeger:
    image: jaegertracing/all-in-one:latest
    network_mode: "host" # acesso local no host
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: 9411
     
    # ports:
    #   - "5775:5775"
    #   - "6831:6831"
    #   - "6832:6832"
    #   - "5778:5778"
    #   - "16686:16686"
    #   - "14268:14268"
    #   - "14250:14250"
    #   - "9411:9411"
      




